/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelPedidosRouteImport } from './routes/painel/pedidos'
import { Route as PainelMotoboyRouteImport } from './routes/painel/motoboy'
import { Route as PainelAdminRouteImport } from './routes/painel/admin'
import { Route as PainelProdutosRouteImport } from './routes/painel/produtos'
import { Route as PainelFinanceiroRouteImport } from './routes/painel/financeiro'
import { Route as PainelRelatoriosRouteImport } from './routes/painel/relatorios'
import { Route as PainelCategoriasRouteImport } from './routes/painel/categorias'
import { Route as PainelPromocoesRouteImport } from './routes/painel/promocoes'
import { Route as PainelAtendentesRouteImport } from './routes/painel/atendentes'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel/configuracoes'
import { Route as PainelClientesRouteImport } from './routes/painel/clientes'
import { Route as PainelLoginRouteImport } from './routes/painel/login'
import { Route as PainelIndexRouteImport } from './routes/painel/index'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const PainelPedidosRoute = PainelPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => PainelRoute,
} as any)

const PainelMotoboyRoute = PainelMotoboyRouteImport.update({
  id: '/motoboy',
  path: '/motoboy',
  getParentRoute: () => PainelRoute,
} as any)

const PainelAdminRoute = PainelAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PainelRoute,
} as any)

const PainelProdutosRoute = PainelProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => PainelRoute,
} as any)

const PainelFinanceiroRoute = PainelFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PainelRoute,
} as any)

const PainelRelatoriosRoute = PainelRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PainelRoute,
} as any)

const PainelCategoriasRoute = PainelCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => PainelRoute,
} as any)

const PainelPromocoesRoute = PainelPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => PainelRoute,
} as any)

const PainelAtendentesRoute = PainelAtendentesRouteImport.update({
  id: '/atendentes',
  path: '/atendentes',
  getParentRoute: () => PainelRoute,
} as any)

const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)

const PainelClientesRoute = PainelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => PainelRoute,
} as any)

const PainelLoginRoute = PainelLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PainelRoute,
} as any)

const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/admin': typeof PainelAdminRoute
  '/painel/motoboy': typeof PainelMotoboyRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/atendentes': typeof PainelAtendentesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel/': typeof PainelIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/motoboy': typeof PainelMotoboyRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/atendentes': typeof PainelAtendentesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel': typeof PainelIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/admin': typeof PainelAdminRoute
  '/painel/motoboy': typeof PainelMotoboyRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/atendentes': typeof PainelAtendentesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel/': typeof PainelIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/painel' | '/painel/admin' | '/painel/motoboy' | '/painel/pedidos' | '/painel/produtos' | '/painel/financeiro' | '/painel/relatorios' | '/painel/categorias' | '/painel/promocoes' | '/painel/atendentes' | '/painel/configuracoes' | '/painel/clientes' | '/painel/login' | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel' | '/painel/admin' | '/painel/motoboy' | '/painel/pedidos' | '/painel/produtos' | '/painel/financeiro' | '/painel/relatorios' | '/painel/categorias' | '/painel/promocoes' | '/painel/atendentes' | '/painel/configuracoes' | '/painel/clientes' | '/painel/login'
  id: '__root__' | '/' | '/painel' | '/painel/admin' | '/painel/motoboy' | '/painel/pedidos' | '/painel/produtos' | '/painel/financeiro' | '/painel/relatorios' | '/painel/categorias' | '/painel/promocoes' | '/painel/atendentes' | '/painel/configuracoes' | '/painel/clientes' | '/painel/login' | '/painel/'
  fileRoutesById: FileRoutesById
}

export interface PainelRouteChildren {
  PainelAdminRoute: typeof PainelAdminRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelMotoboyRoute: typeof PainelMotoboyRoute
  PainelPedidosRoute: typeof PainelPedidosRoute
  PainelProdutosRoute: typeof PainelProdutosRoute
  PainelFinanceiroRoute: typeof PainelFinanceiroRoute
  PainelRelatoriosRoute: typeof PainelRelatoriosRoute
  PainelCategoriasRoute: typeof PainelCategoriasRoute
  PainelPromocoesRoute: typeof PainelPromocoesRoute
  PainelAtendentesRoute: typeof PainelAtendentesRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelClientesRoute: typeof PainelClientesRoute
  PainelLoginRoute: typeof PainelLoginRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAdminRoute,
  PainelIndexRoute,
  PainelMotoboyRoute,
  PainelPedidosRoute,
  PainelProdutosRoute,
  PainelFinanceiroRoute,
  PainelRelatoriosRoute,
  PainelCategoriasRoute,
  PainelPromocoesRoute,
  PainelAtendentesRoute,
  PainelConfiguracoesRoute,
  PainelClientesRoute,
  PainelLoginRoute,
}

const PainelRouteWithChildren = PainelRoute._addFileChildren(PainelRouteChildren)

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/pedidos': {
      id: '/painel/pedidos'
      path: '/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof PainelPedidosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/motoboy': {
      id: '/painel/motoboy'
      path: '/motoboy'
      fullPath: '/painel/motoboy'
      preLoaderRoute: typeof PainelMotoboyRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/admin': {
      id: '/painel/admin'
      path: '/admin'
      fullPath: '/painel/admin'
      preLoaderRoute: typeof PainelAdminRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/produtos': {
      id: '/painel/produtos'
      path: '/produtos'
      fullPath: '/painel/produtos'
      preLoaderRoute: typeof PainelProdutosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/financeiro': {
      id: '/painel/financeiro'
      path: '/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof PainelFinanceiroRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/relatorios': {
      id: '/painel/relatorios'
      path: '/relatorios'
      fullPath: '/painel/relatorios'
      preLoaderRoute: typeof PainelRelatoriosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/categorias': {
      id: '/painel/categorias'
      path: '/categorias'
      fullPath: '/painel/categorias'
      preLoaderRoute: typeof PainelCategoriasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/promocoes': {
      id: '/painel/promocoes'
      path: '/promocoes'
      fullPath: '/painel/promocoes'
      preLoaderRoute: typeof PainelPromocoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/atendentes': {
      id: '/painel/atendentes'
      path: '/atendentes'
      fullPath: '/painel/atendentes'
      preLoaderRoute: typeof PainelAtendentesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/clientes': {
      id: '/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof PainelClientesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/login': {
      id: '/painel/login'
      path: '/login'
      fullPath: '/painel/login'
      preLoaderRoute: typeof PainelLoginRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  PainelRoute: PainelRouteWithChildren,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
