-- Core Bora de Batata dashboard schema.
-- Public catalog data is readable without login. Internal operational data is
-- protected with RLS and role checks based on public.profiles.

create type public.app_role as enum ('admin', 'attendant', 'courier');
create type public.order_status as enum ('received', 'preparing', 'ready', 'delivery', 'completed', 'cancelled');
create type public.promotion_kind as enum ('percent', 'fixed', 'combo');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role public.app_role not null default 'attendant',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null check (char_length(name) between 1 and 80),
  description text not null default '' check (char_length(description) <= 500),
  sort_order integer not null default 0 check (sort_order >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.categories(id) on delete restrict,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null check (char_length(name) between 1 and 120),
  description text not null default '' check (char_length(description) <= 1200),
  base_price numeric(10,2) not null check (base_price between 0 and 100000),
  image_url text not null default '' check (char_length(image_url) <= 2048),
  variant_label text check (variant_label is null or char_length(variant_label) <= 80),
  custom_groups jsonb not null default '[]'::jsonb check (jsonb_typeof(custom_groups) = 'array'),
  badge text check (badge is null or char_length(badge) <= 40),
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  slug text not null check (slug ~ '^[a-z0-9-]+$'),
  label text not null check (char_length(label) between 1 and 100),
  price numeric(10,2) not null check (price between 0 and 100000),
  sort_order integer not null default 0 check (sort_order >= 0),
  active boolean not null default true,
  unique (product_id, slug)
);

create table public.promotions (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 120),
  code text unique check (code is null or code ~ '^[A-Z0-9_-]{2,40}$'),
  kind public.promotion_kind not null,
  value numeric(10,2) check (value is null or value between 0 and 100000),
  benefit_text text not null default '' check (char_length(benefit_text) <= 160),
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  uses integer not null default 0 check (uses >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at > starts_at),
  check (usage_limit is null or uses <= usage_limit)
);

create table public.store_settings (
  id boolean primary key default true check (id),
  store_name text not null default 'Bora de Batata' check (char_length(store_name) between 1 and 120),
  whatsapp text not null default '5521990543204' check (char_length(whatsapp) <= 30),
  city text not null default '' check (char_length(city) <= 120),
  address text not null default '' check (char_length(address) <= 300),
  opens_at time,
  closes_at time,
  accepting_orders boolean not null default true,
  automatic_whatsapp boolean not null default true,
  payment_pix boolean not null default true,
  payment_card boolean not null default true,
  payment_cash boolean not null default true,
  delivery_amount numeric(10,2) check (delivery_amount is null or delivery_amount between 0 and 10000),
  delivery_every_km numeric(8,2) not null default 1.5 check (delivery_every_km > 0),
  delivery_minimum_fee numeric(10,2) not null default 0 check (delivery_minimum_fee >= 0),
  delivery_maximum_distance_km numeric(8,2) check (delivery_maximum_distance_km is null or delivery_maximum_distance_km > 0),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  display_number bigint generated by default as identity unique,
  customer_name text not null check (char_length(customer_name) between 1 and 120),
  customer_phone text check (customer_phone is null or char_length(customer_phone) <= 40),
  channel text not null default 'site' check (char_length(channel) <= 40),
  payment_method text check (payment_method is null or char_length(payment_method) <= 40),
  subtotal numeric(10,2) not null default 0 check (subtotal between 0 and 100000),
  delivery_fee numeric(10,2) check (delivery_fee is null or delivery_fee between 0 and 10000),
  total numeric(10,2) not null default 0 check (total between 0 and 100000),
  notes text check (notes is null or char_length(notes) <= 1000),
  address text check (address is null or char_length(address) <= 500),
  neighborhood text check (neighborhood is null or char_length(neighborhood) <= 120),
  status public.order_status not null default 'received',
  attendant_id uuid references public.profiles(id) on delete set null,
  courier_id uuid references public.profiles(id) on delete set null,
  accepted_at timestamptz,
  ready_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null check (char_length(product_name) between 1 and 160),
  variant_label text check (variant_label is null or char_length(variant_label) <= 120),
  quantity integer not null default 1 check (quantity between 1 and 100),
  unit_price numeric(10,2) not null check (unit_price between 0 and 100000),
  options jsonb not null default '[]'::jsonb check (jsonb_typeof(options) = 'array')
);

create table public.expenses (
  id uuid primary key default gen_random_uuid(),
  category text not null check (char_length(category) between 1 and 80),
  description text not null check (char_length(description) between 1 and 300),
  amount numeric(10,2) not null check (amount between 0 and 1000000),
  paid_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index categories_sort_order_idx on public.categories (sort_order, name);
create index products_category_active_idx on public.products (category_id, active);
create index product_variants_product_idx on public.product_variants (product_id, sort_order);
create index promotions_active_dates_idx on public.promotions (active, starts_at, ends_at);
create index orders_status_created_idx on public.orders (status, created_at desc);
create index orders_courier_idx on public.orders (courier_id, status, created_at desc);
create index orders_attendant_idx on public.orders (attendant_id, status, created_at desc);
create index order_items_order_idx on public.order_items (order_id);
create index expenses_paid_at_idx on public.expenses (paid_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger categories_set_updated_at before update on public.categories
for each row execute function public.set_updated_at();
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();
create trigger promotions_set_updated_at before update on public.promotions
for each row execute function public.set_updated_at();
create trigger store_settings_set_updated_at before update on public.store_settings
for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role
  from public.profiles
  where id = (select auth.uid())
    and active = true
  limit 1
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(public.current_app_role() = 'admin'::public.app_role, false)
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(public.current_app_role() in ('admin'::public.app_role, 'attendant'::public.app_role), false)
$$;

revoke all on function public.current_app_role() from public;
revoke all on function public.is_admin() from public;
revoke all on function public.is_staff() from public;
grant execute on function public.current_app_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_staff() to authenticated;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.promotions enable row level security;
alter table public.store_settings enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.expenses enable row level security;

revoke all on table public.profiles, public.categories, public.products, public.product_variants,
  public.promotions, public.store_settings, public.orders, public.order_items, public.expenses
from anon, authenticated;

grant select on public.categories, public.products, public.product_variants, public.store_settings to anon;
grant select on public.categories, public.products, public.product_variants, public.store_settings to authenticated;
grant select on public.profiles, public.promotions, public.orders, public.order_items to authenticated;
grant insert, update on public.orders, public.order_items to authenticated;
grant insert, update, delete on public.categories, public.products, public.product_variants, public.promotions to authenticated;
grant update on public.store_settings to authenticated;
grant update on public.profiles to authenticated;
grant select, insert, update, delete on public.expenses to authenticated;

create policy profiles_read_self
on public.profiles for select to authenticated
using ((select auth.uid()) = id);

create policy profiles_admin_read_all
on public.profiles for select to authenticated
using (public.is_admin());

create policy profiles_admin_update
on public.profiles for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy categories_public_read_active
on public.categories for select to anon, authenticated
using (active = true);

create policy categories_admin_read_all
on public.categories for select to authenticated
using (public.is_admin());

create policy categories_admin_insert
on public.categories for insert to authenticated
with check (public.is_admin());

create policy categories_admin_update
on public.categories for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy categories_admin_delete
on public.categories for delete to authenticated
using (public.is_admin());

create policy products_public_read_active
on public.products for select to anon, authenticated
using (active = true);

create policy products_admin_read_all
on public.products for select to authenticated
using (public.is_admin());

create policy products_admin_insert
on public.products for insert to authenticated
with check (public.is_admin());

create policy products_admin_update
on public.products for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy products_admin_delete
on public.products for delete to authenticated
using (public.is_admin());

create policy variants_public_read_active
on public.product_variants for select to anon, authenticated
using (
  active = true
  and exists (
    select 1 from public.products p
    where p.id = product_variants.product_id and p.active = true
  )
);

create policy variants_admin_read_all
on public.product_variants for select to authenticated
using (public.is_admin());

create policy variants_admin_insert
on public.product_variants for insert to authenticated
with check (public.is_admin());

create policy variants_admin_update
on public.product_variants for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy variants_admin_delete
on public.product_variants for delete to authenticated
using (public.is_admin());

create policy promotions_staff_read
on public.promotions for select to authenticated
using (public.is_staff());

create policy promotions_admin_insert
on public.promotions for insert to authenticated
with check (public.is_admin());

create policy promotions_admin_update
on public.promotions for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy promotions_admin_delete
on public.promotions for delete to authenticated
using (public.is_admin());

create policy settings_public_read
on public.store_settings for select to anon, authenticated
using (true);

create policy settings_admin_update
on public.store_settings for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy orders_staff_read
on public.orders for select to authenticated
using (public.is_staff());

create policy orders_courier_read_assigned
on public.orders for select to authenticated
using (
  public.current_app_role() = 'courier'::public.app_role
  and courier_id = (select auth.uid())
);

create policy orders_staff_insert
on public.orders for insert to authenticated
with check (public.is_staff());

create policy orders_staff_update
on public.orders for update to authenticated
using (public.is_staff())
with check (public.is_staff());

create policy items_staff_read
on public.order_items for select to authenticated
using (
  public.is_staff()
  or exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and o.courier_id = (select auth.uid())
  )
);

create policy items_staff_insert
on public.order_items for insert to authenticated
with check (public.is_staff());

create policy items_staff_update
on public.order_items for update to authenticated
using (public.is_staff())
with check (public.is_staff());

create policy expenses_admin_all
on public.expenses for all to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.store_settings (
  id, store_name, whatsapp, opens_at, closes_at, accepting_orders, automatic_whatsapp
) values (
  true, 'Bora de Batata', '5521990543204', '19:00', '00:30', true, true
);

insert into public.categories (slug, name, description, sort_order) values
  ('batatas', 'Batatas recheadas', 'Batatas de 300g e 500g com recheios variados.', 1),
  ('pasteis', 'Pastéis', 'Pastéis montáveis e opções completas.', 2),
  ('bebidas', 'Bebidas', 'Bebidas para acompanhar o pedido.', 3);

insert into public.products (category_id, slug, name, description, base_price, image_url, variant_label, custom_groups)
select c.id, v.slug, v.name, v.description, v.base_price, '/bora-hero.png', 'tamanho',
  '[{"id":"retirar","label":"Retirar ingredientes","options":["Mussarela derretida","Cebolinha fresca","Bacon"],"min":0,"max":3,"hint":"Retire o que preferir da finalização."}]'::jsonb
from public.categories c
cross join (values
  ('batata-strogonoff', 'Strogonoff de frango', 'Batata recheada com strogonoff de frango. Finalização com mussarela, cebolinha e bacon.', 19.00::numeric),
  ('batata-carne-cheddar', 'Carne moída com cheddar', 'Batata recheada com carne moída com cheddar. Finalização com mussarela, cebolinha e bacon.', 20.00::numeric),
  ('batata-carne-catupiry', 'Carne moída com catupiry', 'Batata recheada com carne moída com catupiry. Finalização com mussarela, cebolinha e bacon.', 20.00::numeric),
  ('batata-bacon-cheddar', 'Bacon com cheddar', 'Batata recheada com bacon com cheddar. Finalização com mussarela, cebolinha e bacon.', 17.50::numeric),
  ('batata-bacon-catupiry', 'Bacon com catupiry', 'Batata recheada com bacon com catupiry. Finalização com mussarela, cebolinha e bacon.', 17.50::numeric),
  ('batata-calabresa-cheddar', 'Calabresa com cheddar', 'Batata recheada com calabresa com cheddar. Finalização com mussarela, cebolinha e bacon.', 16.00::numeric),
  ('batata-calabresa-catupiry', 'Calabresa com catupiry', 'Batata recheada com calabresa com catupiry. Finalização com mussarela, cebolinha e bacon.', 16.00::numeric)
) as v(slug, name, description, base_price)
where c.slug = 'batatas';

insert into public.products (category_id, slug, name, description, base_price, image_url, custom_groups)
select c.id, 'pastel-montavel', 'Monte seu pastel',
  'Pastel grande e crocante. Escolha de 1 a 7 ingredientes do seu jeito.',
  18.99, '/bora-hero.png',
  '[{"id":"recheios","label":"Ingredientes do pastel","options":["Carne","Frango","Uva-passa","Milho","Ervilha","Presunto","Queijo","Azeitona","Cebola","Tomate","Cheddar","Catupiry","Bacon","Calabresa"],"min":1,"max":7,"hint":"Escolha até 7 opções. Todas inclusas no preço."}]'::jsonb
from public.categories c where c.slug = 'pasteis';

insert into public.products (category_id, slug, name, description, base_price, image_url, custom_groups)
select c.id, 'pastel-completo', 'Pastel com tudo dentro',
  'Pastel grande com todas as opções de recheio.',
  24.99, '/bora-hero.png',
  '[{"id":"retirar","label":"Retirar ingredientes","options":["Carne","Frango","Uva-passa","Milho","Ervilha","Presunto","Queijo","Azeitona","Cebola","Tomate","Cheddar","Catupiry","Bacon","Calabresa"],"min":0,"max":14,"hint":"Retire os ingredientes que você não quiser."}]'::jsonb
from public.categories c where c.slug = 'pasteis';

insert into public.products (category_id, slug, name, description, base_price, image_url)
select c.id, 'refrigerante-lata', 'Refrigerante lata',
  'Para acompanhar seu pedido. Consulte os sabores disponíveis pelo WhatsApp.',
  6.80, '/bora-drink.svg'
from public.categories c where c.slug = 'bebidas';

insert into public.products (category_id, slug, name, description, base_price, image_url)
select c.id, 'guaracamp', 'Guaracamp',
  'Seu Guaracamp para acompanhar a batata ou o pastel.',
  2.50, '/bora-drink.svg'
from public.categories c where c.slug = 'bebidas';

insert into public.product_variants (product_id, slug, label, price, sort_order)
select p.id, v.slug, v.label, v.price, v.sort_order
from public.products p
join (values
  ('batata-strogonoff', 'pequena', 'Pequena • 300g', 19.00::numeric, 1),
  ('batata-strogonoff', 'grande', 'Grande • 500g', 22.50::numeric, 2),
  ('batata-carne-cheddar', 'pequena', 'Pequena • 300g', 20.00::numeric, 1),
  ('batata-carne-cheddar', 'grande', 'Grande • 500g', 24.00::numeric, 2),
  ('batata-carne-catupiry', 'pequena', 'Pequena • 300g', 20.00::numeric, 1),
  ('batata-carne-catupiry', 'grande', 'Grande • 500g', 24.00::numeric, 2),
  ('batata-bacon-cheddar', 'pequena', 'Pequena • 300g', 17.50::numeric, 1),
  ('batata-bacon-cheddar', 'grande', 'Grande • 500g', 21.50::numeric, 2),
  ('batata-bacon-catupiry', 'pequena', 'Pequena • 300g', 17.50::numeric, 1),
  ('batata-bacon-catupiry', 'grande', 'Grande • 500g', 21.50::numeric, 2),
  ('batata-calabresa-cheddar', 'pequena', 'Pequena • 300g', 16.00::numeric, 1),
  ('batata-calabresa-cheddar', 'grande', 'Grande • 500g', 20.00::numeric, 2),
  ('batata-calabresa-catupiry', 'pequena', 'Pequena • 300g', 16.00::numeric, 1),
  ('batata-calabresa-catupiry', 'grande', 'Grande • 500g', 20.00::numeric, 2)
) as v(product_slug, slug, label, price, sort_order)
  on p.slug = v.product_slug;

comment on table public.profiles is 'Authenticated Bora staff profiles and app roles.';
comment on table public.orders is 'Operational orders. Customer checkout persistence will be wired in a later migration.';
